### ISSUE TITLE
How to use this project

### ISSUE THREAD

**Issue by joneswe** [Matthiaas/Braincode#1]
Hey,
I have seen your project @openCodes in KA. Nice Job Guys.
Can you plz write a short info how to use it?
What do I need and how can I start it?

thx

**Comment by camodude009** [comment]
Hi :)
You can either:
- load the project (/src is in /RainCode) and modify the source code to load c files (you can load multiple files at once this way) then run as normal application
- use the  precompiled Jar - command line args: [0]: path to c file, [1]: path to image (where it should be placed); both paths are relative
- host everything in /frontend with a webserver like apache (our web code is NOT checked for any security vulnerabilities!)

Some example files that work well are located in res. (cat.c and head.c look very good)
The code will generate 8k images by default, although you can change that in the source code.
This along with other settings are found at the very top of the main class, here you can also change the seeds of the random number generators (will make the image look slightly different).
